export type SeedPaymentCode = {
  code: string
  description: string
  parcelas: number
  category: string
  type: "receita" | "despesa"
}

export const PAYMENT_CODES_SEED: SeedPaymentCode[] = [
  { code: "0", description: "À VISTA", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "ANT", description: "ANTECIPADO", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "CARTAO", description: "CARTAO DE CREDITO", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "CARTAO03", description: "CARTAO 03", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "CARTAO04", description: "CARTAO 04", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "CARTAO07", description: "CARTAO 07", parcelas: 7, category: "Compras", type: "despesa" },
  { code: "CARTAO10", description: "CARTAO 10X", parcelas: 10, category: "Compras", type: "despesa" },
  { code: "CARTAO12", description: "CARTAO 12 X", parcelas: 12, category: "Compras", type: "despesa" },
  { code: "CARTAO2", description: "CARTAO 2X", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "CARTAO05", description: "CARTAO 5 X", parcelas: 5, category: "Compras", type: "despesa" },
  { code: "CARTAO6", description: "CARTAO 6X", parcelas: 6, category: "Compras", type: "despesa" },
  { code: "CARTAO08", description: "CARTAO 8 X", parcelas: 8, category: "Compras", type: "despesa" },
  { code: "CARTAO09", description: "CARTAO 9X", parcelas: 9, category: "Compras", type: "despesa" },
  { code: "COFINS", description: "COFINS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "CSLL", description: "CSLL", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "DIA", description: "DIARIO", parcelas: 22, category: "Compras", type: "despesa" },
  { code: "FCP", description: "FCP", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "FGTS", description: "FGTS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "20H", description: "FIXO DIA 20", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "12F", description: "FIXO 12", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "15F", description: "FIXO 15", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "FIXO25", description: "FIXO 25", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "ICMS", description: "ICMS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "29D", description: "IMPOSTO", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "25D", description: "IMPOSTOS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "30DIAS", description: "IMPOSTOS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "INSS", description: "INSS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "IPI", description: "IPI", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "IRRF", description: "IRRF", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "20D", description: "ISS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "ISS", description: "ISS - XXXXXXXXXXX", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "IMP", description: "Parcelas Importadas", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "PIS", description: "PIS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "CONTSOC", description: "Pis/Cofins/Csll", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "PREV10", description: "PREVISAO 10D", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "PREV15", description: "PREVISAO 15D", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "010", description: "0/10", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "10PAR", description: "01/30/60/90/120/150/180/210/230/260/290", parcelas: 11, category: "Compras", type: "despesa" },
  { code: "0B", description: "0/20/40", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "028", description: "0/28/56/84 DIAS", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "05P", description: "0/28/56/84/112", parcelas: 5, category: "Compras", type: "despesa" },
  { code: "03", description: "03 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "07G", description: "0/30/60", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "030", description: "0/30/60/90/120/150/180 DIAS", parcelas: 7, category: "Compras", type: "despesa" },
  { code: "16P", description: "0/30/60/90/120/150/180/210/240/270/300/330/360/390/420/450", parcelas: 16, category: "Compras", type: "despesa" },
  { code: "029", description: "0/30/60/90/120/150/180/220/250", parcelas: 9, category: "Compras", type: "despesa" },
  { code: "07", description: "07 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "007", description: "0/7/14/21 DIAS", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "07F", description: "07/21", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "07B", description: "07/21/42", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "07D", description: "07/28/56/84", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "07E", description: "07/30", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "07C", description: "07/30/60/90", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "9", description: "09 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "10", description: "10 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "100", description: "100/120 DIAS", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "10B", description: "10/20/30/40/50/60/70 DIAS", parcelas: 7, category: "Compras", type: "despesa" },
  { code: "10A", description: "10/20/30/40/50/60/70/80/90/100 DIAS", parcelas: 10, category: "Compras", type: "despesa" },
  { code: "12", description: "12 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "12PARC", description: "12 PARCELAS", parcelas: 12, category: "Compras", type: "despesa" },
  { code: "120", description: "120 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "14", description: "14 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "14A", description: "14/21/28 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "14C", description: "14/21/28/35/42 DIAS", parcelas: 5, category: "Compras", type: "despesa" },
  { code: "14B", description: "14/28 DIAS", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "15", description: "15 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "150", description: "150 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "15A", description: "15/29 DIAS", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "15B", description: "15/30/45/60/75 DIAS", parcelas: 5, category: "Compras", type: "despesa" },
  { code: "15C", description: "15/30/45/60/75/90/120", parcelas: 7, category: "Compras", type: "despesa" },
  { code: "17", description: "17 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "19", description: "19 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "20", description: "20 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "20C", description: "20/27/34 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "20A", description: "20/40 DDL", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "20B", description: "20/40/60 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "21", description: "21 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "21B", description: "21/28/35 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "21G", description: "21/28/35/42 DIAS", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "21D", description: "21/28/35/42/49/56 DIAS", parcelas: 6, category: "Compras", type: "despesa" },
  { code: "21A", description: "21/35 DIAS", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "21F", description: "21/35/42 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "21E", description: "21/35/42/49 DIAS", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "03P", description: "21/35/51", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "21C", description: "21/42 DIAS", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "23", description: "23 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "24", description: "24 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "25", description: "25 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "25A", description: "25/50/75 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "28", description: "28 DDL", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "28A", description: "28/35 DDL", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "28B", description: "28/35/42 DDL", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "28H", description: "28/35/42/49 DIAS", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "28L", description: "28/35/42/49/56/63 DIAS", parcelas: 6, category: "Compras", type: "despesa" },
  { code: "28N", description: "28/35/42/56", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "28J", description: "28/35/42/70 DIAS", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "28I", description: "28/38/48 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "28D", description: "28/42 DIAS", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "28C", description: "28/42/56 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "28G", description: "28/45/52/60/75 DIAS", parcelas: 5, category: "Compras", type: "despesa" },
  { code: "28M", description: "28/45/60 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "28E", description: "28/56 DIAS", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "28F", description: "28/56/84 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "28K", description: "28/56/84/112/140 DIAS", parcelas: 5, category: "Compras", type: "despesa" },
  { code: "29P", description: "29 PARCELAS", parcelas: 29, category: "Compras", type: "despesa" },
  { code: "30", description: "30 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "30H", description: "30/40/50 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "30O", description: "30/40/50/60 DIAS", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "30F", description: "30/42 DIAS", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "30E", description: "30/45 dias", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "30M", description: "30/45/52/60/75/90 DIAS", parcelas: 6, category: "Compras", type: "despesa" },
  { code: "30D", description: "30/45/60 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "30P", description: "30/45/60/75 DIAS", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "30G", description: "30/45/60/75/90 DIAS", parcelas: 5, category: "Compras", type: "despesa" },
  { code: "30Q", description: "30/58/86/114/142/170/198 DIAS", parcelas: 7, category: "Compras", type: "despesa" },
  { code: "30A", description: "30/60 DDL", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "30N", description: "30/60/75 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "30B", description: "30/60/90 DDL", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "04", description: "30/60/90/120", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "30L", description: "30/60/90/120 DIAS", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "30C", description: "30/60/90/120/150 DIAS", parcelas: 5, category: "Compras", type: "despesa" },
  { code: "30I", description: "30/60/90/120/150/180 DIAS", parcelas: 6, category: "Compras", type: "despesa" },
  { code: "30S", description: "30/60/90/120/150/180/210 DIAS", parcelas: 7, category: "Compras", type: "despesa" },
  { code: "30K", description: "30/60/90/120/150/180/210/240 DIAS", parcelas: 8, category: "Compras", type: "despesa" },
  { code: "30R", description: "30/60/90/120/150/180/210/240/270", parcelas: 9, category: "Compras", type: "despesa" },
  { code: "30J", description: "30/60/90/120/150/180/210/240/270/300 DIAS", parcelas: 10, category: "Compras", type: "despesa" },
  { code: "32", description: "32/49/63 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "35", description: "35 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "35A", description: "35/42 DIAS", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "35F", description: "35/42/49 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "35C", description: "35/42/49/56 DIAS", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "35E", description: "35/42/49/56/63 DIAS", parcelas: 5, category: "Compras", type: "despesa" },
  { code: "35B", description: "35/49 DIAS", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "35G", description: "35/49/63 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "35D", description: "35/70 DIAS", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "37", description: "37/45 DIAS", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "38", description: "38/41/53 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "38A", description: "38/52/66 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "40", description: "40 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "42", description: "42 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "42/60", description: "42 e 60 dias", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "45", description: "45 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "05", description: "5 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "50", description: "50 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "55", description: "55 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "60", description: "60 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "04A", description: "60/70/80/90", parcelas: 4, category: "Compras", type: "despesa" },
  { code: "60A", description: "60/75/90 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
  { code: "07A", description: "7/14/21/28/35 DIAS", parcelas: 5, category: "Compras", type: "despesa" },
  { code: "75", description: "75 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "09", description: "9 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "90", description: "90 DIAS", parcelas: 1, category: "Compras", type: "despesa" },
  { code: "90A", description: "90/120 DIAS", parcelas: 2, category: "Compras", type: "despesa" },
  { code: "90B", description: "90/120/150 DIAS", parcelas: 3, category: "Compras", type: "despesa" },
]
